skip_tags: true
clone_depth: 50

os: Visual Studio 2015

environment:
  matrix:
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86"
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"


platform:
    - x64

build_script:
  # - ps: choco install microsoft-build-tools --version 14.0.25420.1
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda update conda --quiet
  - conda install numpy cython nose pandas pytest scipy --quiet
  - conda install -c numba numba --quiet
  - python -m pip install -e .
  - set "GIT_DIR=%cd%"

test_script:
  - pytest randomgen

on_success:
  - cd %GIT_DIR%\
  - python benchmark.py
