name: Build using clang-cl on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    runs-on: windows-latest
    name: Build wheel using clang-cl on Windows
    strategy:
      fail-fast: false
      matrix:
        python: [cp312]
    defaults:
      run:
        shell: bash
    env:
      BUILD_COMMIT: "main"
      CIBW_BUILD: ${{ matrix.python }}-*
      CIBW_ARCHS_LINUX: x86_64
      CIBW_ARCHS_MACOS: native
      CIBW_SKIP: "pp* *-musllinux_* *-win32"
      CIBW_TEST_REQUIRES: pytest pytest-xdist
      CIBW_TEST_COMMAND: python -c "import randomgen; randomgen.test(['--skip-slow','-n','2'])"
      CIBW_ENVIRONMENT: 'CC="clang-cl"'
      MKL_NUM_THREADS: 1
      OMP_NUM_THREADS: 1
      OPENLAS_NUM_THREADS: 1

    steps:
      - uses: actions/checkout@v6

      - name: Get clang-cl version
        run: clang-cl --version

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3
        with:
          output-dir: wheelhouse

